## this is how you mark properties for inheritance (&blerf)
# kvm-hypervisor-role: &hypervisor
#   service: purpledrank.services.kvm.KVMService

## this is how you inherit properties (<< : *blerf)
# beastmode1:
#   host: beastmode1.mgmt.aperobot.net
#   << : *hypervisor

zfs-role: &zfs
  service: purpledrank.services.zfs.ZFSService

kvm-role: &kvm
  service: purpledrank.services.kvm.KVMService

redis-config: &redis-config
  host: 127.0.0.1
  port: 6379

test-service: &test-service
  service: purpledrank.services.test.TestService

sync-service: &sync
  redis:
    << : *redis-config

twaughthammer-sq46yxz: &twaughthammer
  host: twaughthammer.work.aperobot.net
  port: 9292
  sourceid: twaughthammer
  << : *zfs

beastmode1-rsaj8th: &beastmode
  host: beastmode1.mgmt.aperobot.net
  port: 9292
  sourceid: beastmode
  << : *kvm

collector-service: &collector
  sources:
    - <<       : *twaughthammer
      name     : zpool_props
      method   : get_zpool_properties
      interval : 30
      args     : []
    - <<       : *twaughthammer
      name     : zpool_status
      method   : get_zpool_status
      interval : 30
      args     : []
    - <<       : *twaughthammer
      name     : zvol_properties
      method   : get_zvol_properties
      interval : 30
      args     : []
    - <<       : *twaughthammer
      name     : itadm_properties
      method   : get_itadm_properties
      interval : 30
      args     : []
    - <<       : *twaughthammer
      name     : stmf_targets
      method   : get_stmf_properties
      interval : 30
      args     : []
    - <<       : *twaughthammer
      name     : cfgadm_disks
      method   : get_cfgadm_disks
      interval : 30
      args     : []
    - <<       : *beastmode
      name     : kvm_vms
      method   : get_all_vms
      interval : 30
      args     : []
  service: purpledrank.services.rediscollector.RedisCollectorService
  redis:
    << : *redis-config

xander-xerbuyi:
  host: xander.esc.aperobot.net
  << : *collector

