kvm-hypervisor-role: &hypervisor
  service: purpledrank.services.kvm.KVMService

zfs-role: &zfs
  service: purpledrank.services.zfs.ZFSService

test-service: &test-service
  service: purpledrank.services.test.TestService

# this is how you inherit properties
beastmode1:
  host: beastmode1.mgmt.aperobot.net
  << : *hypervisor

twaughthammer-sq46yxz:
  host: twaughthammer.mgmt.aperobot.net
  << : *zfs
